"""create the table captcha

Revision ID: 5d2bb54e26ca
Revises: 4f7fb3e535fc
Create Date: 2022-12-03 19:51:35.551935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2bb54e26ca'
down_revision = '4f7fb3e535fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('captchaId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('createdTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('captchaId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha')
    # ### end Alembic commands ###
