"""add columns to table employer table

Revision ID: c05fd28c294b
Revises: 5cb134cb8b0a
Create Date: 2022-12-12 12:40:18.238006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05fd28c294b'
down_revision = '5cb134cb8b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('CEO', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dateOfEstablishment', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('placeOfEstablishment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('staff', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_column('staff')
        batch_op.drop_column('placeOfEstablishment')
        batch_op.drop_column('dateOfEstablishment')
        batch_op.drop_column('CEO')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
