"""add table captchaPasswordChange

Revision ID: c74f14afab0a
Revises: 
Create Date: 2022-12-08 17:25:25.104784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74f14afab0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captchaPasswordChange',
    sa.Column('captchaId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('createdTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('captchaId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captchaPasswordChange')
    # ### end Alembic commands ###
