"""change the column place to location in table employer

Revision ID: dca7b9b63fef
Revises: b71a8c5bd30a
Create Date: 2022-12-12 13:21:22.017612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca7b9b63fef'
down_revision = 'b71a8c5bd30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.drop_column('placeOfEstablishment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placeOfEstablishment', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
