"""set receivedResumes nullable false

Revision ID: ecedea0c66b3
Revises: 373ecca9ae25
Create Date: 2022-12-13 16:35:13.781431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecedea0c66b3'
down_revision = '373ecca9ae25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('receivedResumes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('receivedResumes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
